server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/
logging:
  level:
    org.springframework.web: WARN
    com.travelling: DEBUG
